// Dev/Epm.LGoods.UI/epm.lgoods.reactclient/src/components/VendorDashboard/manage-product/ProductList.tsx
import { useEffect, useState } from "react";
import "../../../styles/product-list.css";
import { fetchProducts } from "../../../services/fetchProducts";
import { Products, Filters } from "../../../types/type";
import Sidebar from "./Sidebar";
import ProductTable from "./ProductTable";
import Menu from "../../PriceMapping/Menu";

import Modal from "react-modal"
import ProductCreationModal from '../product-creation-modal/ProductCreationModal';
import styles from "./ProductList.module.css";
import Header from "../../Header";
import Footer from "../../Footer";

Modal.setAppElement('#root');

const ProductList = () => {
    
    const [products, setProducts] = useState<Products[]>([]);
    const [filters, setFilters] = useState<Filters>({
        productType: "",
        categories: "",
        manufacturer: "",
        countryOfOrigin: "",
        price: ""
    });

    const [showSidebar, setShowSidebar] = useState(false);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [showMenu, setShowMenu] = useState(false);
    
    useEffect(() => {
        const loadProducts = async () => {
            const productList = await fetchProducts(filters);
            setProducts(productList);
        };

        loadProducts();
    }, [filters]);

    const openModal = () => {
        setIsModalOpen(true);
    };
    
    const closeModal = () => setIsModalOpen(false);

    const loadProducts = async () => {
        const productList = await fetchProducts(filters);
        setProducts(productList);
    };

    const handleDelete = async (productId: string) => {
        const confirmDelete = window.confirm("Are you sure you want to permanently delete this product?");
        if (confirmDelete) {
            window.alert("Product deleted successfully");
            loadProducts();
        }
    };

    const handleUpdate = (productId: string) => {
       
    };

    const toggleMenu = () => {
        setShowMenu(!showMenu);
    };

    const closeMenu = () => {
        setShowMenu(false);
    };

    const toggleSidebar = () => {
        setShowSidebar(!showSidebar);
    };

    const closeSidebar = () => {
        setShowSidebar(false);
    };

    const applyFilters = (newFilters: Filters) => {
        setFilters(newFilters);
        closeSidebar();
    };
  
    return (
        <div className="page-container">
            <Header />
            <Menu isOpen={showMenu} onClose={closeMenu} />   
         <div className={`product-list-container ${showMenu ? 'shifted' : ''}`}>
            <div className="top-bar">
                <button className="menu-toggle-btn" onClick={toggleMenu}>
                &#9776;
                </button>
                <button className="filter-toggle-btn" onClick={toggleSidebar}>
                    <i className="fas fa-filter"></i>
                </button>
                <button className="create-btn" onClick={openModal}>Create New Product</button>
            </div>

            <Modal
                isOpen={isModalOpen}
                onRequestClose={closeModal}
                contentLabel="Add Product Modal"
                className={styles.modal}
                overlayClassName={styles.overlay}
            >
                <ProductCreationModal closeModal={closeModal} />
            </Modal>  

            {showSidebar && <Sidebar onApplyFilters={applyFilters}  closeSidebar={closeSidebar}/>}
            {showMenu && <Menu isOpen={showMenu} onClose={closeMenu} />}
            {products.length === 0 ? (
                <div className="no-products">No products found</div>
            ): (
                <ProductTable products={products} handleUpdate={handleUpdate} handleDelete={handleDelete} />
            )}
            </div>
            <Footer />
        </div>
    );
};

export default ProductList;

// Dev/Epm.LGoods.UI/epm.lgoods.angularclient/src/app/components/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from '../../models/product';
import { ProductService } from '../../services/product.service';
import { ProductFilter } from '../../models/product-filter';
import { Price } from '../../models/price.model';
import { Router } from '@angular/router';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {
  products: Product[] = [];
  filters: ProductFilter = {
    productName: "",
    productType: "",
    countryOfOrigin: ""
  };
  showSidebar = false;

  constructor(private productService: ProductService,private router: Router) { }

  ngOnInit(): void {
    this.loadProducts();
  }

  loadProducts(): void {
    const isFiltersEmpty = Object.values(this.filters).every(filter => !filter);
    console.log(this.filters);
    console.log(isFiltersEmpty);
    if (isFiltersEmpty) {
      this.productService.fetchAllProducts().subscribe({
        next: (response: any) => {
          const productList = response.$values || [];
          this.products = Array.isArray(productList) ? productList : [];
        },
        error: (error) => {
          console.error('Error fetching products:', error);
          this.products = [];
        }
      });
    } else {
      this.productService.fetchProducts(this.filters).subscribe({
        next: (response: any) => {
          const productList = response.$values || [];
          this.products = Array.isArray(productList) ? productList : [];
        },
        error: (error) => {
          console.error('Error fetching products:', error);
          this.products = [];
        }
      });
    }
  }

  handleDelete(productId: number): void {
    const confirmDelete = window.confirm("Are you sure you want to permanently delete this product?");
    if (confirmDelete) {
      this.productService.deleteProduct(productId).subscribe({
        next: () => this.loadProducts(),
        error: (error) => console.error('Error deleting product:', error)
      });
    }
  }

  toggleSidebar(): void {
    this.showSidebar = !this.showSidebar;
  }

  closeSidebar(): void {
    this.showSidebar = false;
  }

  applyFilters(newFilters: ProductFilter): void {
    this.filters = newFilters;
    this.closeSidebar();
    this.loadProducts();
  }

  handlecreate(): void {
    this.router.navigate(['/product-creation']);
  }
  handleUpdate(productId: number): void {
    console.log('Navigating to product-creation with productId:', productId);
    this.router.navigate(['/product-update',productId])
  }

  navigateToTagSelector(productId: number): void {
    console.log(productId);
    this.router.navigate([`/product-layout/${productId}`]);
  }
}

<div class="product-list-container">
  <div class="top-bar">
    <button class="filter-toggle-btn" (click)="toggleSidebar()">&#9776;</button>
    <button class="create-btn" (click)="handlecreate()">Create New Product</button>
  </div>

  <app-product-filter *ngIf="showSidebar" (onApplyFilters)="applyFilters($event)" (closeSidebar)="closeSidebar()"></app-product-filter>
  <h3>PRODUCT LIST</h3>
  <table class="product-table">
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Product Type</th>
        <th>Country of Origin</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let product of products">
        <td>
          <a (click)="navigateToTagSelector(product.productId)" style="cursor: pointer; color: blue; text-decoration: underline;">
            {{ product.productName }}
          </a>
        </td>
        <td>{{ product.productType }}</td>
        <td>{{ product.countryOfOrigin }}</td>
        <td>
          <button class="update-btn" (click)="handleUpdate(product.productId)">Update</button>
          <button class="delete-btn" (click)="handleDelete(product.productId)">Delete</button>


        </td>
      </tr>
      <tr *ngIf="!products || !products.length">
        <td colspan="4">No products found</td>
      </tr>
    </tbody>
  </table>
</div>
