// Dev/Epm.LGoods.UI/epm.lgoods.reactclient/src/components/Header.tsx
// import React from "react";
// import "../styles/header.css";
// import img from "../assets/localgoodslogo.webp";
// import { Link } from "react-router-dom";

// const Header = () => {
//     return (
//         <header>
//             <nav>
//                 <div className="left-section">
//                     <img src={img} alt="Local Goods Logo" className="logo" />
//                     <Link  to={"/product-list"}  className="manage-product">
//                         <em className="fa-solid fa-box"></em>
//                         <span>Manage Product</span>
                        
//                     </Link>
//                 </div>
//                 <div className="right-icons">
//                     <em className="fa-solid fa-user"></em>
//                     <a href="./" className="shake">
//                         <em className="fa-solid fa-bell"></em>
//                     </a>
//                 </div>
//             </nav>
//         </header>
//     );
// };

// export default Header;


import { useState } from 'react';
import '../styles/header.css';
import img from '../assets/localgoodslogo.webp';
import { Link } from 'react-router-dom';

const Header = () => {
    const [isCatalogHovered, setIsCatalogHovered] = useState(false);

    return (
        <header>
            <nav>
                <div className="left-section">
                    <img src={img} alt="Local Goods Logo" className="logo" />
                    <div className="catalog"
                         onMouseEnter={() => setIsCatalogHovered(true)}
                         onMouseLeave={() => setIsCatalogHovered(false)}>
                        <ul className="catalog-main-ul">
                            <li className="catalog-main">
                                    <em className="fa-solid fa-box"></em>
                                    <span>Catalog</span>
                            </li>
                        </ul>
                        {isCatalogHovered && (
                            <ul className="dropdown">
                                <li><Link to="/manage-products" className="dropdown-item">Manage Products</Link></li>
                                <li><Link to="/categories" className="dropdown-item">Categories</Link></li>
                            </ul>
                        )}
                    </div>
                </div>
                <div className="right-icons">
                    <em className="fa-solid fa-user"></em>
                    <a href="./" className="shake">
                        <em className="fa-solid fa-bell"></em>
                    </a>
                </div>
            </nav>
        </header>
    );
};

export default Header;

// Dev/Epm.LGoods.UI/epm.lgoods.angularclient/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { NgModule } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {

}

<header>
  <nav>
    <img src="\assests\images\localgoodslogo.webp" alt="Local Goods Logo" class="logo">


    <div class="dashboard-menu first" tabindex="0">
      <a href="/dashboard" class="dashboard-link">
        <div class="dashboard-icon">
          <em class="fa-solid fa-house"></em>
        </div>
        <span class="dashboard-text">Dashboard</span>
      </a>
    </div>


    <div class="sales-menu first" tabindex="0">
      <em class="fa-solid fa-chart-simple"></em>
      <span>Sales</span>
      <ul class="sales-dropdown">
        <li><a href="/manage-orders">Orders</a></li>
        <li><a href="/shipments">Shipments</a></li>
      </ul>
    </div>

    <div class="sales-menu ml-4" tabindex="0">
      <em class="fa-solid fa-cube"></em>
      <span>Catalog</span>
      <ul class="sales-dropdown">
        <li><a href="/product-layout"><em class="fa-solid fa-cubes mr-2"></em>Manage Products</a></li>
        <li><a href="/product-stock"><em class="fa-solid fa-cubes mr-2"></em>Low Stock Report</a></li>
        <li><a href="/category-list"><em class="fa-brands fa-hive mr-2"></em>Categories</a></li>
      </ul>
    </div>



    <div class="right-icons">
      <em class="fa-solid fa-user"></em>
      <a class="shake"><em class="fa-solid fa-bell"></em></a>
    </div>
  </nav>
</header>
